<a href="https://colab.research.google.com/github/gplinkage/Excercises/blob/Class-Notes%2FExercise%2FMy-OwnExcercise/Home_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
df= pd.read_csv('/content/homeprices_mlr.csv')

In [19]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [20]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [21]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan, strategy='median')
df.iloc[:, 1:2]=imputer.fit_transform(df.iloc[:, 1:2])

In [22]:
X= df.iloc[:, :-1].values
y= df.iloc[:, -1].values

In [23]:
print(X)

[[2.6e+03 3.0e+00 2.0e+01]
 [3.0e+03 4.0e+00 1.5e+01]
 [3.2e+03 4.0e+00 1.8e+01]
 [3.6e+03 3.0e+00 3.0e+01]
 [4.0e+03 5.0e+00 8.0e+00]
 [4.1e+03 6.0e+00 8.0e+00]]


In [24]:
y

array([550000, 565000, 610000, 595000, 760000, 810000])

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [26]:
X_train, X_test, y_train, y_test

(array([[3.0e+03, 4.0e+00, 1.5e+01],
        [3.6e+03, 3.0e+00, 3.0e+01],
        [2.6e+03, 3.0e+00, 2.0e+01],
        [4.0e+03, 5.0e+00, 8.0e+00]]),
 array([[4.1e+03, 6.0e+00, 8.0e+00],
        [3.2e+03, 4.0e+00, 1.8e+01]]),
 array([565000, 595000, 550000, 760000]),
 array([810000, 610000]))

In [27]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [28]:
reg.predict(X_test)

array([608500., 554875.])

In [29]:
from sklearn.metrics import r2_score
r2_score(y_test, reg.predict(X_test))

-1.1820507812499903

In [30]:
df2= pd.read_csv('/content/50_Startups.csv')
df2.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [31]:
df2.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [51]:
X = df2.loc[:, ['R&D Spend', 'R&D Spend', 'State']].values
y = df2.iloc[:, -1].values

In [52]:
X, y

(array([[165349.2, 165349.2, 'New York'],
        [162597.7, 162597.7, 'California'],
        [153441.51, 153441.51, 'Florida'],
        [144372.41, 144372.41, 'New York'],
        [142107.34, 142107.34, 'Florida'],
        [131876.9, 131876.9, 'New York'],
        [134615.46, 134615.46, 'California'],
        [130298.13, 130298.13, 'Florida'],
        [120542.52, 120542.52, 'New York'],
        [123334.88, 123334.88, 'California'],
        [101913.08, 101913.08, 'Florida'],
        [100671.96, 100671.96, 'California'],
        [93863.75, 93863.75, 'Florida'],
        [91992.39, 91992.39, 'California'],
        [119943.24, 119943.24, 'Florida'],
        [114523.61, 114523.61, 'New York'],
        [78013.11, 78013.11, 'California'],
        [94657.16, 94657.16, 'New York'],
        [91749.16, 91749.16, 'Florida'],
        [86419.7, 86419.7, 'New York'],
        [76253.86, 76253.86, 'California'],
        [78389.47, 78389.47, 'New York'],
        [73994.56, 73994.56, 'Florida'],
        

In [53]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [54]:
X

array([[0.0, 0.0, 1.0, 165349.2, 165349.2],
       [1.0, 0.0, 0.0, 162597.7, 162597.7],
       [0.0, 1.0, 0.0, 153441.51, 153441.51],
       [0.0, 0.0, 1.0, 144372.41, 144372.41],
       [0.0, 1.0, 0.0, 142107.34, 142107.34],
       [0.0, 0.0, 1.0, 131876.9, 131876.9],
       [1.0, 0.0, 0.0, 134615.46, 134615.46],
       [0.0, 1.0, 0.0, 130298.13, 130298.13],
       [0.0, 0.0, 1.0, 120542.52, 120542.52],
       [1.0, 0.0, 0.0, 123334.88, 123334.88],
       [0.0, 1.0, 0.0, 101913.08, 101913.08],
       [1.0, 0.0, 0.0, 100671.96, 100671.96],
       [0.0, 1.0, 0.0, 93863.75, 93863.75],
       [1.0, 0.0, 0.0, 91992.39, 91992.39],
       [0.0, 1.0, 0.0, 119943.24, 119943.24],
       [0.0, 0.0, 1.0, 114523.61, 114523.61],
       [1.0, 0.0, 0.0, 78013.11, 78013.11],
       [0.0, 0.0, 1.0, 94657.16, 94657.16],
       [0.0, 1.0, 0.0, 91749.16, 91749.16],
       [0.0, 0.0, 1.0, 86419.7, 86419.7],
       [1.0, 0.0, 0.0, 76253.86, 76253.86],
       [0.0, 0.0, 1.0, 78389.47, 78389.47],
       [0.0,

In [55]:
from sklearn.feature_selection import f_regression
f_regression(X, y)

(array([1.04306966e+00, 6.57495535e-01, 4.72749794e-02, 8.49788904e+02,
        8.49788904e+02]),
 array([3.12228656e-01, 4.21447913e-01, 8.28796347e-01, 3.50032224e-32,
        3.50032224e-32]))

In [56]:
p_values = f_regression(X, y)[1]
p_values.round(3)

array([0.312, 0.421, 0.829, 0.   , 0.   ])

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [58]:
X_train, X_test, y_train, y_test

(array([[0.0, 1.0, 0.0, 55493.95, 55493.95],
        [0.0, 0.0, 1.0, 46014.02, 46014.02],
        [0.0, 1.0, 0.0, 75328.87, 75328.87],
        [1.0, 0.0, 0.0, 46426.07, 46426.07],
        [0.0, 1.0, 0.0, 91749.16, 91749.16],
        [0.0, 1.0, 0.0, 130298.13, 130298.13],
        [0.0, 1.0, 0.0, 119943.24, 119943.24],
        [0.0, 0.0, 1.0, 1000.23, 1000.23],
        [0.0, 0.0, 1.0, 542.05, 542.05],
        [0.0, 0.0, 1.0, 65605.48, 65605.48],
        [0.0, 0.0, 1.0, 114523.61, 114523.61],
        [0.0, 1.0, 0.0, 61994.48, 61994.48],
        [1.0, 0.0, 0.0, 63408.86, 63408.86],
        [1.0, 0.0, 0.0, 78013.11, 78013.11],
        [1.0, 0.0, 0.0, 23640.93, 23640.93],
        [1.0, 0.0, 0.0, 76253.86, 76253.86],
        [0.0, 0.0, 1.0, 15505.73, 15505.73],
        [0.0, 0.0, 1.0, 120542.52, 120542.52],
        [1.0, 0.0, 0.0, 91992.39, 91992.39],
        [1.0, 0.0, 0.0, 64664.71, 64664.71],
        [0.0, 0.0, 1.0, 131876.9, 131876.9],
        [0.0, 0.0, 1.0, 94657.16, 94657.16],
        

In [59]:
from sklearn.linear_model import LinearRegression
reg= LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [60]:
reg.predict(X_test)

array([104968.88239768, 133957.33622212, 135497.03491305,  72485.31055717,
       179362.04719688, 109820.27677127,  65657.67476864, 100480.71994665,
       111730.61659317, 169713.51906829])

In [61]:
from sklearn.metrics import r2_score
r2_score(y_test, reg.predict(X_test))

0.9471689304016058