<a href="https://colab.research.google.com/github/gplinkage/Excercises/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np


In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
v= np.diag([1,2,3,4,5])
print(v)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [7]:
z= np.diag(1+np.arange(4), k=1)
print(z)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [8]:
z= np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [11]:
lst1= [11,12, 33, 45,65,77]
arr1= np.array(lst1)
print(arr1)
print(type(arr1))

[11 12 33 45 65 77]
<class 'numpy.ndarray'>


In [16]:
a = np.array(42)
b= np.array([1,2,3,4,5])
c= np.array([[1,2,3],[4,5,6]])
d= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
!pip install pandas
import pandas as pd


In [22]:
df = pd.read_csv('/content/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [30]:
# prompt: Using dataframe df: convert df to sql table and perform print

import sqlite3

# Create a connection to an in-memory SQLite database
conn = sqlite3.connect(':memory:')

# Convert the DataFrame to an SQL table
df.to_sql('my_table', conn, if_exists='replace', index=False)

# Execute a query to print the first few rows of the table
cursor = conn.cursor()
cursor.execute("SELECT * FROM my_table LIMIT 5")
rows = cursor.fetchall()
for row in rows:
    print(row)

# Close the connection
conn.close()


(1, 15634602, 'Hargrave', 619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88, 1)
(2, 15647311, 'Hill', 608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58, 0)
(3, 15619304, 'Onio', 502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57, 1)
(4, 15701354, 'Boni', 699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63, 0)
(5, 15737888, 'Mitchell', 850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1, 0)


df_table
